# Generated by Django 5.2.17 on 2026-09-11 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField(help_text="Description de l'activité telle que saisie par le client.", verbose_name='Activité')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('generee', 'Générée'), ('payee', 'Payée'), ('telechargee', 'Téléchargée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(help_text='Spécification structurée (feuilles, colonnes, formules, etc.).', verbose_name='Contenu JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='orders.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Spécification',
                'verbose_name_plural': 'Spécifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
