# Generated by Django 5.2.17 on 2026-09-20 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_attente_paiement', 'En attente de paiement'), ('generee', 'Générée'), ('payee', 'Payée'), ('telechargee', 'Téléchargée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
    ]
