# Generated by Django 5.2.17 on 2026-09-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='generated_file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fichier Excel généré'),
        ),
    ]
